#!/usr/bin/env bash
# ============================================================
# scripts/setup.sh
# ローカル初期セットアップ: parameters.json と .env を生成
# Usage: bash scripts/setup.sh
# ============================================================
set -euo pipefail

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
info()  { echo -e "${GREEN}[INFO]${NC}  $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error() { echo -e "${RED}[ERROR]${NC} $*"; exit 1; }

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"

# ── 前提ツール確認 ─────────────────────────────────────────────
info "Checking prerequisites..."
for cmd in aws docker; do
  command -v "$cmd" &>/dev/null || error "$cmd is not installed."
done
info "Prerequisites OK"

# ── AWS認証確認 ───────────────────────────────────────────────
info "Checking AWS credentials..."
aws sts get-caller-identity --output table \
  || error "AWS credentials not configured. Run: aws configure"

# ── Bedrockモデルアクセス確認 ─────────────────────────────────
info "Checking Bedrock model access (ap-northeast-1)..."
MODELS=$(aws bedrock list-foundation-models \
  --region ap-northeast-1 \
  --query "summaryList[?contains(modelId,'claude-sonnet')].modelId" \
  --output text 2>/dev/null || echo "")

if [ -z "$MODELS" ]; then
  warn "Bedrock models not found. Enable model access:"
  warn "  → https://ap-northeast-1.console.aws.amazon.com/bedrock/home?region=ap-northeast-1#/modelaccess"
else
  info "Bedrock OK. Available Claude Sonnet models:"
  echo "$MODELS"
fi

# ── docker/.env 生成 ──────────────────────────────────────────
ENV_FILE="$REPO_ROOT/docker/.env"
if [ ! -f "$ENV_FILE" ]; then
  info "Generating $ENV_FILE ..."
  PASSWORD=$(openssl rand -base64 16 | tr -dc 'a-zA-Z0-9' | head -c 20)
  cat > "$ENV_FILE" <<EOF
# Auto-generated by setup.sh — $(date)
CODE_SERVER_PASSWORD=${PASSWORD}
AWS_DEFAULT_REGION=ap-northeast-1
ANTHROPIC_MODEL=us.anthropic.claude-sonnet-4-5
CLAUDE_CODE_USE_BEDROCK=1
EOF
  info ".env created. Password: ${PASSWORD}"
  warn "このパスワードを控えておいてください（再表示されません）"
else
  warn "$ENV_FILE already exists, skipping."
  PASSWORD=$(grep CODE_SERVER_PASSWORD "$ENV_FILE" | cut -d= -f2)
fi

# ── cfn/parameters.json 生成 ──────────────────────────────────
PARAMS_FILE="$REPO_ROOT/cfn/parameters.json"
if [ ! -f "$PARAMS_FILE" ]; then
  info "Generating $PARAMS_FILE ..."
  MY_IP=$(curl -s https://checkip.amazonaws.com)/32
  cat > "$PARAMS_FILE" <<EOF
[
  { "ParameterKey": "ProjectName",        "ParameterValue": "ai-dev-env" },
  { "ParameterKey": "InstanceType",       "ParameterValue": "t3.medium" },
  { "ParameterKey": "RootVolumeSize",     "ParameterValue": "30" },
  { "ParameterKey": "VpcCidr",            "ParameterValue": "10.0.0.0/16" },
  { "ParameterKey": "SubnetCidr",         "ParameterValue": "10.0.1.0/24" },
  { "ParameterKey": "AllowedCidr",        "ParameterValue": "${MY_IP}" },
  { "ParameterKey": "KeyPairName",        "ParameterValue": "" },
  { "ParameterKey": "CodeServerPassword", "ParameterValue": "${PASSWORD}" },
  { "ParameterKey": "AwsRegion",          "ParameterValue": "ap-northeast-1" }
]
EOF
  info "parameters.json created (your IP: ${MY_IP})"
else
  warn "$PARAMS_FILE already exists, skipping."
fi

# ── 完了メッセージ ─────────────────────────────────────────────
echo ""
info "===== Setup complete ====="
info "Next steps:"
echo ""
echo "  【CloudFormation でEC2を構築】"
echo "    cd cfn"
echo "    aws cloudformation deploy \\"
echo "      --template-file template.yaml \\"
echo "      --stack-name ai-dev-env \\"
echo "      --parameter-overrides file://parameters.json \\"
echo "      --capabilities CAPABILITY_NAMED_IAM \\"
echo "      --region ap-northeast-1"
echo ""
echo "  【Docker でローカル起動】"
echo "    cd docker && docker compose up -d"
echo ""
echo "  【スタック削除】"
echo "    aws cloudformation delete-stack --stack-name ai-dev-env --region ap-northeast-1"
