#!/usr/bin/env bash
# ============================================================
# scripts/setup.sh
# Local setup: prepares .env and terraform.tfvars
# Usage: bash scripts/setup.sh
# ============================================================
set -euo pipefail

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
info()  { echo -e "${GREEN}[INFO]${NC}  $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error() { echo -e "${RED}[ERROR]${NC} $*"; exit 1; }

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"

# ── Prerequisite check ────────────────────────────────────────
info "Checking prerequisites..."
for cmd in aws terraform docker; do
  command -v "$cmd" &>/dev/null || error "$cmd is not installed. Please install it first."
done
info "All prerequisites OK"

# ── AWS credential check ──────────────────────────────────────
info "Checking AWS credentials..."
aws sts get-caller-identity --output table || error "AWS credentials not configured. Run: aws configure"

# ── Bedrock model access check ────────────────────────────────
info "Checking Bedrock model access (ap-northeast-1)..."
MODELS=$(aws bedrock list-foundation-models \
  --region ap-northeast-1 \
  --query "summaryList[?contains(modelId,\`claude-sonnet\`)].modelId" \
  --output text 2>/dev/null || echo "")

if [ -z "$MODELS" ]; then
  warn "Could not list Bedrock models. Make sure you have enabled model access in the AWS console."
  warn "  → https://ap-northeast-1.console.aws.amazon.com/bedrock/home?region=ap-northeast-1#/modelaccess"
else
  info "Bedrock accessible. Available Claude Sonnet models:"
  echo "$MODELS"
fi

# ── Generate .env ─────────────────────────────────────────────
ENV_FILE="$REPO_ROOT/docker/.env"
if [ ! -f "$ENV_FILE" ]; then
  info "Generating $ENV_FILE ..."
  PASSWORD=$(openssl rand -base64 16 | tr -dc 'a-zA-Z0-9' | head -c 20)
  cat > "$ENV_FILE" <<EOF
# Auto-generated by setup.sh — $(date)
CODE_SERVER_PASSWORD=${PASSWORD}
AWS_DEFAULT_REGION=ap-northeast-1
ANTHROPIC_MODEL=us.anthropic.claude-sonnet-4-5
CLAUDE_CODE_USE_BEDROCK=1
EOF
  info ".env created. Password: $PASSWORD"
  warn "Store this password safely — it won't be shown again."
else
  warn "$ENV_FILE already exists, skipping."
fi

# ── Generate terraform.tfvars ─────────────────────────────────
TFVARS="$REPO_ROOT/terraform/terraform.tfvars"
if [ ! -f "$TFVARS" ]; then
  info "Generating $TFVARS ..."
  MY_IP=$(curl -s https://checkip.amazonaws.com)/32
  PASSWORD=$(grep CODE_SERVER_PASSWORD "$ENV_FILE" | cut -d= -f2)
  cat > "$TFVARS" <<EOF
# Auto-generated by setup.sh — $(date)
aws_region           = "ap-northeast-1"
project_name         = "ai-dev-env"
instance_type        = "t3.medium"
root_volume_size     = 30
allowed_cidr_blocks  = ["${MY_IP}"]
public_key_path      = "~/.ssh/id_rsa.pub"
code_server_password = "${PASSWORD}"
EOF
  info "terraform.tfvars created (your IP: $MY_IP)"
else
  warn "$TFVARS already exists, skipping."
fi

echo ""
info "===== Setup complete ====="
info "Next steps:"
echo "  Docker:    cd docker && docker compose up -d"
echo "  Terraform: cd terraform && terraform init && terraform apply"
